// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file vss.proto (package vss, syntax proto3)
/* eslint-disable */
// @ts-nocheck — generated code uses enum syntax incompatible with erasableSyntaxOnly

import type { GenEnum, GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2'
import { enumDesc, fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv2'
import type { Message } from '@bufbuild/protobuf'

/**
 * Describes the file vss.proto.
 */
export const file_vss: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Cgl2c3MucHJvdG8SA3ZzcyIxChBHZXRPYmplY3RSZXF1ZXN0EhAKCHN0b3JlX2lkGAEgASgJEgsKA2tleRgCIAEoCSIxChFHZXRPYmplY3RSZXNwb25zZRIcCgV2YWx1ZRgCIAEoCzINLnZzcy5LZXlWYWx1ZSKjAQoQUHV0T2JqZWN0UmVxdWVzdBIQCghzdG9yZV9pZBgBIAEoCRIbCg5nbG9iYWxfdmVyc2lvbhgCIAEoA0gAiAEBEigKEXRyYW5zYWN0aW9uX2l0ZW1zGAMgAygLMg0udnNzLktleVZhbHVlEiMKDGRlbGV0ZV9pdGVtcxgEIAMoCzINLnZzcy5LZXlWYWx1ZUIRCg9fZ2xvYmFsX3ZlcnNpb24iEwoRUHV0T2JqZWN0UmVzcG9uc2UiSQoTRGVsZXRlT2JqZWN0UmVxdWVzdBIQCghzdG9yZV9pZBgBIAEoCRIgCglrZXlfdmFsdWUYAiABKAsyDS52c3MuS2V5VmFsdWUiFgoURGVsZXRlT2JqZWN0UmVzcG9uc2UioAEKFkxpc3RLZXlWZXJzaW9uc1JlcXVlc3QSEAoIc3RvcmVfaWQYASABKAkSFwoKa2V5X3ByZWZpeBgCIAEoCUgAiAEBEhYKCXBhZ2Vfc2l6ZRgDIAEoBUgBiAEBEhcKCnBhZ2VfdG9rZW4YBCABKAlIAogBAUINCgtfa2V5X3ByZWZpeEIMCgpfcGFnZV9zaXplQg0KC19wYWdlX3Rva2VuIqABChdMaXN0S2V5VmVyc2lvbnNSZXNwb25zZRIjCgxrZXlfdmVyc2lvbnMYASADKAsyDS52c3MuS2V5VmFsdWUSHAoPbmV4dF9wYWdlX3Rva2VuGAIgASgJSACIAQESGwoOZ2xvYmFsX3ZlcnNpb24YAyABKANIAYgBAUISChBfbmV4dF9wYWdlX3Rva2VuQhEKD19nbG9iYWxfdmVyc2lvbiJECg1FcnJvclJlc3BvbnNlEiIKCmVycm9yX2NvZGUYASABKA4yDi52c3MuRXJyb3JDb2RlEg8KB21lc3NhZ2UYAiABKAkiNwoIS2V5VmFsdWUSCwoDa2V5GAEgASgJEg8KB3ZlcnNpb24YAiABKAMSDQoFdmFsdWUYAyABKAwiTgoIU3RvcmFibGUSDAoEZGF0YRgBIAEoDBI0ChNlbmNyeXB0aW9uX21ldGFkYXRhGAIgASgLMhcudnNzLkVuY3J5cHRpb25NZXRhZGF0YSJHChJFbmNyeXB0aW9uTWV0YWRhdGESFQoNY2lwaGVyX2Zvcm1hdBgBIAEoCRINCgVub25jZRgCIAEoDBILCgN0YWcYAyABKAwiLwoNUGxhaW50ZXh0QmxvYhINCgV2YWx1ZRgBIAEoDBIPCgd2ZXJzaW9uGAIgASgDKp0BCglFcnJvckNvZGUSCwoHVU5LTk9XThAAEhYKEkNPTkZMSUNUX0VYQ0VQVElPThABEh0KGUlOVkFMSURfUkVRVUVTVF9FWENFUFRJT04QAhIdChlJTlRFUk5BTF9TRVJWRVJfRVhDRVBUSU9OEAMSGQoVTk9fU1VDSF9LRVlfRVhDRVBUSU9OEAQSEgoOQVVUSF9FWENFUFRJT04QBUILCgdvcmcudnNzUAFiBnByb3RvMw'
  )

/**
 * Request payload to be used for `GetObject` API call to server.
 *
 * @generated from message vss.GetObjectRequest
 */
export type GetObjectRequest = Message<'vss.GetObjectRequest'> & {
  /**
   * `store_id` is a keyspace identifier.
   * Ref: https://en.wikipedia.org/wiki/Keyspace_(distributed_data_store)
   * All APIs operate within a single `store_id`.
   * It is up to clients to use single or multiple stores for their use-case.
   * This can be used for client-isolation/ rate-limiting / throttling on the server-side.
   * Authorization and billing can also be performed at the `store_id` level.
   *
   * @generated from field: string store_id = 1;
   */
  storeId: string

  /**
   * The key of the value to be fetched.
   *
   * If the specified `key` does not exist, returns `ErrorCode.NO_SUCH_KEY_EXCEPTION` in the
   * the `ErrorResponse`.
   *
   * Consistency Guarantee:
   * Get(read) operations against a `key` are consistent reads and will reflect all previous writes,
   * since Put/Write provides read-after-write and read-after-update consistency guarantees.
   *
   * Read Isolation:
   * Get/Read operations against a `key` are ensured to have read-committed isolation.
   * Ref: https://en.wikipedia.org/wiki/Isolation_(database_systems)#Read_committed
   *
   * @generated from field: string key = 2;
   */
  key: string
}

/**
 * Describes the message vss.GetObjectRequest.
 * Use `create(GetObjectRequestSchema)` to create a new message.
 */
export const GetObjectRequestSchema: GenMessage<GetObjectRequest> =
  /*@__PURE__*/
  messageDesc(file_vss, 0)

/**
 * Server response for `GetObject` API.
 *
 * @generated from message vss.GetObjectResponse
 */
export type GetObjectResponse = Message<'vss.GetObjectResponse'> & {
  /**
   * Fetched `value` and `version` along with the corresponding `key` in the request.
   *
   * @generated from field: vss.KeyValue value = 2;
   */
  value?: KeyValue
}

/**
 * Describes the message vss.GetObjectResponse.
 * Use `create(GetObjectResponseSchema)` to create a new message.
 */
export const GetObjectResponseSchema: GenMessage<GetObjectResponse> =
  /*@__PURE__*/
  messageDesc(file_vss, 1)

/**
 * Request payload to be used for `PutObject` API call to server.
 *
 * @generated from message vss.PutObjectRequest
 */
export type PutObjectRequest = Message<'vss.PutObjectRequest'> & {
  /**
   * `store_id` is a keyspace identifier.
   * Ref: https://en.wikipedia.org/wiki/Keyspace_(distributed_data_store)
   * All APIs operate within a single `store_id`.
   * It is up to clients to use single or multiple stores for their use-case.
   * This can be used for client-isolation/ rate-limiting / throttling on the server-side.
   * Authorization and billing can also be performed at the `store_id` level.
   *
   * @generated from field: string store_id = 1;
   */
  storeId: string

  /**
   * `global_version` is a sequence-number/version of the whole store. This can be used for versioning
   * and ensures that multiple updates in case of multiple devices can only be done linearly, even
   * if those updates did not directly conflict with each other based on keys/`transaction_items`.
   *
   * If present, the write will only succeed if the current server-side `global_version` against
   * the `store_id` is same as in the request.
   * Clients are expected to store (client-side) the global version against `store_id`.
   * The request must contain their client-side value of `global_version` if global versioning and
   * conflict detection is desired.
   *
   * For the first write of the store, global version should be '0'. If the write succeeds, clients
   * must increment their global version (client-side) by 1.
   * The server increments `global_version` (server-side) for every successful write, hence this
   * client-side increment is required to ensure matching versions. This updated global version
   * should be used in subsequent `PutObjectRequest`s for the store.
   *
   * Requests with a conflicting version will fail with `CONFLICT_EXCEPTION` as ErrorCode.
   *
   * @generated from field: optional int64 global_version = 2;
   */
  globalVersion?: bigint

  /**
   * Items to be written as a result of this `PutObjectRequest`.
   *
   * In an item, each `key` is supplied with its corresponding `value` and `version`.
   * Clients can choose to encrypt the keys client-side in order to obfuscate their usage patterns.
   * If the write is successful, the previous `value` corresponding to the `key` will be overwritten.
   *
   * Multiple items in `transaction_items` and `delete_items` of a single `PutObjectRequest` are written in
   * a database-transaction in an all-or-nothing fashion.
   * All Items in a single `PutObjectRequest` must have distinct keys.
   *
   * Key-level versioning (Conditional Write):
   *   Clients are expected to store a `version` against every `key`.
   *   The write will succeed if the current DB version against the `key` is the same as in the request.
   *   When initiating a `PutObjectRequest`, the request should contain their client-side `version`
   *   for that key-value.
   *
   *   For the first write of any `key`, the `version` should be '0'. If the write succeeds, the client
   *   must increment their corresponding key versions (client-side) by 1.
   *   The server increments key versions (server-side) for every successful write, hence this
   *   client-side increment is required to ensure matching versions. These updated key versions should
   *   be used in subsequent `PutObjectRequest`s for the keys.
   *
   *   Requests with a conflicting/mismatched version will fail with `CONFLICT_EXCEPTION` as ErrorCode
   *   for conditional writes.
   *
   * Skipping key-level versioning (Non-conditional Write):
   *   If you wish to skip key-level version checks, set the `version` against the `key` to '-1'.
   *   This will perform a non-conditional write query, after which the `version` against the `key`
   *   is reset to '1'. Hence, the next `PutObjectRequest` for the `key` can be either
   *   a non-conditional write or a conditional write with `version` set to `1`.
   *
   * Considerations for transactions:
   * Transaction writes of multiple items have a performance overhead, hence it is recommended to use
   * them only if required by the client application to ensure logic/code correctness.
   * That is, `transaction_items` are not a substitute for batch-write of multiple unrelated items.
   * When a write of multiple unrelated items is desired, it is recommended to use separate
   * `PutObjectRequest`s.
   *
   * Consistency guarantee:
   * All `PutObjectRequest`s are strongly consistent i.e. they provide read-after-write and
   * read-after-update consistency guarantees.
   *
   * @generated from field: repeated vss.KeyValue transaction_items = 3;
   */
  transactionItems: KeyValue[]

  /**
   * Items to be deleted as a result of this `PutObjectRequest`.
   *
   * Each item in the `delete_items` field consists of a `key` and its corresponding `version`.
   *
   * Key-Level Versioning (Conditional Delete):
   *   The `version` is used to perform a version check before deleting the item.
   *   The delete will only succeed if the current database version against the `key` is the same as
   *   the `version` specified in the request.
   *
   * Skipping key-level versioning (Non-conditional Delete):
   *   If you wish to skip key-level version checks, set the `version` against the `key` to '-1'.
   *   This will perform a non-conditional delete query.
   *
   * Fails with `CONFLICT_EXCEPTION` as the ErrorCode if:
   *   * The requested item does not exist.
   *   * The requested item does exist but there is a version-number mismatch (in conditional delete)
   *     with the one in the database.
   *
   * Multiple items in the `delete_items` field, along with the `transaction_items`, are written in a
   * database transaction in an all-or-nothing fashion.
   *
   * All items within a single `PutObjectRequest` must have distinct keys.
   *
   * @generated from field: repeated vss.KeyValue delete_items = 4;
   */
  deleteItems: KeyValue[]
}

/**
 * Describes the message vss.PutObjectRequest.
 * Use `create(PutObjectRequestSchema)` to create a new message.
 */
export const PutObjectRequestSchema: GenMessage<PutObjectRequest> =
  /*@__PURE__*/
  messageDesc(file_vss, 2)

/**
 * Server response for `PutObject` API.
 *
 * @generated from message vss.PutObjectResponse
 */
export type PutObjectResponse = Message<'vss.PutObjectResponse'> & {}

/**
 * Describes the message vss.PutObjectResponse.
 * Use `create(PutObjectResponseSchema)` to create a new message.
 */
export const PutObjectResponseSchema: GenMessage<PutObjectResponse> =
  /*@__PURE__*/
  messageDesc(file_vss, 3)

/**
 * Request payload to be used for `DeleteObject` API call to server.
 *
 * @generated from message vss.DeleteObjectRequest
 */
export type DeleteObjectRequest = Message<'vss.DeleteObjectRequest'> & {
  /**
   * `store_id` is a keyspace identifier.
   * Ref: https://en.wikipedia.org/wiki/Keyspace_(distributed_data_store)
   * All APIs operate within a single `store_id`.
   * It is up to clients to use single or multiple stores for their use-case.
   * This can be used for client-isolation/ rate-limiting / throttling on the server-side.
   * Authorization and billing can also be performed at the `store_id` level.
   *
   * @generated from field: string store_id = 1;
   */
  storeId: string

  /**
   * Item to be deleted as a result of this `DeleteObjectRequest`.
   *
   * An item consists of a `key` and its corresponding `version`.
   *
   * Key-level Versioning (Conditional Delete):
   *   The item is only deleted if the current database version against the `key` is the same as
   *   the `version` specified in the request.
   *
   * Skipping key-level versioning (Non-conditional Delete):
   *   If you wish to skip key-level version checks, set the `version` against the `key` to '-1'.
   *   This will perform a non-conditional delete query.
   *
   * This operation is idempotent, that is, multiple delete calls for the same item will not fail.
   *
   * If the requested item does not exist, this operation will not fail.
   * If you wish to perform stricter checks while deleting an item, consider using `PutObject` API.
   *
   * @generated from field: vss.KeyValue key_value = 2;
   */
  keyValue?: KeyValue
}

/**
 * Describes the message vss.DeleteObjectRequest.
 * Use `create(DeleteObjectRequestSchema)` to create a new message.
 */
export const DeleteObjectRequestSchema: GenMessage<DeleteObjectRequest> =
  /*@__PURE__*/
  messageDesc(file_vss, 4)

/**
 * Server response for `DeleteObject` API.
 *
 * @generated from message vss.DeleteObjectResponse
 */
export type DeleteObjectResponse = Message<'vss.DeleteObjectResponse'> & {}

/**
 * Describes the message vss.DeleteObjectResponse.
 * Use `create(DeleteObjectResponseSchema)` to create a new message.
 */
export const DeleteObjectResponseSchema: GenMessage<DeleteObjectResponse> =
  /*@__PURE__*/
  messageDesc(file_vss, 5)

/**
 * Request payload to be used for `ListKeyVersions` API call to server.
 *
 * @generated from message vss.ListKeyVersionsRequest
 */
export type ListKeyVersionsRequest = Message<'vss.ListKeyVersionsRequest'> & {
  /**
   * `store_id` is a keyspace identifier.
   * Ref: https://en.wikipedia.org/wiki/Keyspace_(distributed_data_store)
   * All APIs operate within a single `store_id`.
   * It is up to clients to use single or multiple stores for their use-case.
   * This can be used for client-isolation/ rate-limiting / throttling on the server-side.
   * Authorization and billing can also be performed at the `store_id` level.
   *
   * @generated from field: string store_id = 1;
   */
  storeId: string

  /**
   * A `key_prefix` is a string of characters at the beginning of the key. Prefixes can be used as
   * a way to organize key-values in a similar way to directories.
   *
   * If `key_prefix` is specified, the response results will be limited to those keys that begin with
   * the specified prefix.
   *
   * If no `key_prefix` is specified or it is empty (""), all the keys are eligible to be returned in
   * the response.
   *
   * @generated from field: optional string key_prefix = 2;
   */
  keyPrefix?: string

  /**
   * `page_size` is used by clients to specify the maximum number of results that can be returned by
   * the server.
   * The server may further constrain the maximum number of results returned in a single page.
   * If the `page_size` is 0 or not set, the server will decide the number of results to be returned.
   *
   * @generated from field: optional int32 page_size = 3;
   */
  pageSize?: number

  /**
   * `page_token` is a pagination token.
   *
   * To query for the first page of `ListKeyVersions`, `page_token` must not be specified.
   *
   * For subsequent pages, use the value that was returned as `next_page_token` in the previous
   * page's `ListKeyVersionsResponse`.
   *
   * @generated from field: optional string page_token = 4;
   */
  pageToken?: string
}

/**
 * Describes the message vss.ListKeyVersionsRequest.
 * Use `create(ListKeyVersionsRequestSchema)` to create a new message.
 */
export const ListKeyVersionsRequestSchema: GenMessage<ListKeyVersionsRequest> =
  /*@__PURE__*/
  messageDesc(file_vss, 6)

/**
 * Server response for `ListKeyVersions` API.
 *
 * @generated from message vss.ListKeyVersionsResponse
 */
export type ListKeyVersionsResponse = Message<'vss.ListKeyVersionsResponse'> & {
  /**
   * Fetched keys and versions.
   * Even though this API reuses the `KeyValue` struct, the `value` sub-field will not be set by the server.
   *
   * @generated from field: repeated vss.KeyValue key_versions = 1;
   */
  keyVersions: KeyValue[]

  /**
   * `next_page_token` is a pagination token, used to retrieve the next page of results.
   * Use this value to query for next-page of paginated `ListKeyVersions` operation, by specifying
   * this value as the `page_token` in the next request.
   *
   * If `next_page_token` is empty (""), then the "last page" of results has been processed and
   * there is no more data to be retrieved.
   *
   * If `next_page_token` is not empty, it does not necessarily mean that there is more data in the
   * result set. The only way to know when you have reached the end of the result set is when
   * `next_page_token` is empty.
   *
   * Caution: Clients must not assume a specific number of key_versions to be present in a page for
   * paginated response.
   *
   * @generated from field: optional string next_page_token = 2;
   */
  nextPageToken?: string

  /**
   * `global_version` is a sequence-number/version of the whole store.
   *
   * `global_version` is only returned in response for the first page of the `ListKeyVersionsResponse`
   * and is guaranteed to be read before reading any key-versions.
   *
   * In case of refreshing the complete key-version view on the client-side, correct usage for
   * the returned `global_version` is as following:
   *   1. Read `global_version` from the first page of paginated response and save it as local variable.
   *   2. Update all the `key_versions` on client-side from all the pages of paginated response.
   *   3. Update `global_version` on client_side from the local variable saved in step-1.
   * This ensures that on client-side, all current `key_versions` were stored at `global_version` or later.
   * This guarantee is helpful for ensuring the versioning correctness if using the `global_version`
   * in `PutObject` API and can help avoid the race conditions related to it.
   *
   * @generated from field: optional int64 global_version = 3;
   */
  globalVersion?: bigint
}

/**
 * Describes the message vss.ListKeyVersionsResponse.
 * Use `create(ListKeyVersionsResponseSchema)` to create a new message.
 */
export const ListKeyVersionsResponseSchema: GenMessage<ListKeyVersionsResponse> =
  /*@__PURE__*/
  messageDesc(file_vss, 7)

/**
 * When HttpStatusCode is not ok (200), the response `content` contains a serialized `ErrorResponse`
 * with the relevant `ErrorCode` and `message`
 *
 * @generated from message vss.ErrorResponse
 */
export type ErrorResponse = Message<'vss.ErrorResponse'> & {
  /**
   * The error code uniquely identifying an error condition.
   * It is meant to be read and understood programmatically by code that detects/handles errors by
   * type.
   *
   * @generated from field: vss.ErrorCode error_code = 1;
   */
  errorCode: ErrorCode

  /**
   * The error message containing a generic description of the error condition in English.
   * It is intended for a human audience only and should not be parsed to extract any information
   * programmatically. Client-side code may use it for logging only.
   *
   * @generated from field: string message = 2;
   */
  message: string
}

/**
 * Describes the message vss.ErrorResponse.
 * Use `create(ErrorResponseSchema)` to create a new message.
 */
export const ErrorResponseSchema: GenMessage<ErrorResponse> = /*@__PURE__*/ messageDesc(file_vss, 8)

/**
 * Represents a key-value pair to be stored or retrieved.
 *
 * @generated from message vss.KeyValue
 */
export type KeyValue = Message<'vss.KeyValue'> & {
  /**
   * Key against which the value is stored.
   *
   * @generated from field: string key = 1;
   */
  key: string

  /**
   * Version field is used for key-level versioning.
   * For first write of key, `version` should be '0'. If the write succeeds, clients must increment
   * their corresponding key version (client-side) by 1.
   * The server increments key version (server-side) for every successful write, hence this
   * client-side increment is required to ensure matching versions. These updated key versions should
   * be used in subsequent `PutObjectRequest`s for the keys.
   *
   * @generated from field: int64 version = 2;
   */
  version: bigint

  /**
   * Object value in bytes which is stored (in put) and fetched (in get).
   * Clients must encrypt the secret contents of this blob client-side before sending it over the
   * wire to the server in order to preserve privacy and security.
   * Clients may use a `Storable` object, serialize it and set it here.
   *
   * @generated from field: bytes value = 3;
   */
  value: Uint8Array
}

/**
 * Describes the message vss.KeyValue.
 * Use `create(KeyValueSchema)` to create a new message.
 */
export const KeyValueSchema: GenMessage<KeyValue> = /*@__PURE__*/ messageDesc(file_vss, 9)

/**
 * Represents a storable object that can be serialized and stored as `value` in `PutObjectRequest`.
 * Only provided as a helper object for ease of use by clients.
 * Clients MUST encrypt the `PlaintextBlob` before using it as `data` in `Storable`.
 * The server does not use or read anything from `Storable`, Clients may use its fields as
 * required.
 *
 * @generated from message vss.Storable
 */
export type Storable = Message<'vss.Storable'> & {
  /**
   * Represents an encrypted and serialized `PlaintextBlob`. MUST encrypt the whole `PlaintextBlob`
   * using client-side encryption before setting here.
   *
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array

  /**
   * Represents encryption related metadata
   *
   * @generated from field: vss.EncryptionMetadata encryption_metadata = 2;
   */
  encryptionMetadata?: EncryptionMetadata
}

/**
 * Describes the message vss.Storable.
 * Use `create(StorableSchema)` to create a new message.
 */
export const StorableSchema: GenMessage<Storable> = /*@__PURE__*/ messageDesc(file_vss, 10)

/**
 * Represents encryption related metadata
 *
 * @generated from message vss.EncryptionMetadata
 */
export type EncryptionMetadata = Message<'vss.EncryptionMetadata'> & {
  /**
   * The encryption algorithm used for encrypting the `PlaintextBlob`.
   *
   * @generated from field: string cipher_format = 1;
   */
  cipherFormat: string

  /**
   * The nonce used for encryption. Nonce is a random or unique value used to ensure that the same
   * plaintext results in different ciphertexts every time it is encrypted.
   *
   * @generated from field: bytes nonce = 2;
   */
  nonce: Uint8Array

  /**
   * The authentication tag used for encryption. It provides integrity and authenticity assurance
   * for the encrypted data.
   *
   * @generated from field: bytes tag = 3;
   */
  tag: Uint8Array
}

/**
 * Describes the message vss.EncryptionMetadata.
 * Use `create(EncryptionMetadataSchema)` to create a new message.
 */
export const EncryptionMetadataSchema: GenMessage<EncryptionMetadata> =
  /*@__PURE__*/
  messageDesc(file_vss, 11)

/**
 * Represents a data blob, which is encrypted, serialized and later used in `Storable.data`.
 * Since the whole `Storable.data` is client-side encrypted, the server cannot understand this.
 *
 * @generated from message vss.PlaintextBlob
 */
export type PlaintextBlob = Message<'vss.PlaintextBlob'> & {
  /**
   * The unencrypted value.
   *
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array

  /**
   * The version of the value. Can be used by client to verify version integrity.
   *
   * @generated from field: int64 version = 2;
   */
  version: bigint
}

/**
 * Describes the message vss.PlaintextBlob.
 * Use `create(PlaintextBlobSchema)` to create a new message.
 */
export const PlaintextBlobSchema: GenMessage<PlaintextBlob> =
  /*@__PURE__*/
  messageDesc(file_vss, 12)

/**
 * ErrorCodes to be used in `ErrorResponse`
 *
 * @generated from enum vss.ErrorCode
 */
export enum ErrorCode {
  /**
   * Default protobuf Enum value. Will not be used as `ErrorCode` by server.
   *
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * Used when the request contains mismatched version (either key or global)
   * in `PutObjectRequest`. For more info refer `PutObjectRequest`.
   *
   * @generated from enum value: CONFLICT_EXCEPTION = 1;
   */
  CONFLICT_EXCEPTION = 1,

  /**
   * Used in the following cases:
   *   - The request was missing a required argument.
   *   - The specified argument was invalid, incomplete or in the wrong format.
   *   - The request body of api cannot be deserialized into corresponding protobuf object.
   *
   * @generated from enum value: INVALID_REQUEST_EXCEPTION = 2;
   */
  INVALID_REQUEST_EXCEPTION = 2,

  /**
   * Used when an internal server error occurred, client is probably at no fault and can safely retry
   * this error with exponential backoff.
   *
   * @generated from enum value: INTERNAL_SERVER_EXCEPTION = 3;
   */
  INTERNAL_SERVER_EXCEPTION = 3,

  /**
   * Used when the specified `key` in a `GetObjectRequest` does not exist.
   *
   * @generated from enum value: NO_SUCH_KEY_EXCEPTION = 4;
   */
  NO_SUCH_KEY_EXCEPTION = 4,

  /**
   * Used when authentication fails or in case of an unauthorized request.
   *
   * @generated from enum value: AUTH_EXCEPTION = 5;
   */
  AUTH_EXCEPTION = 5,
}

/**
 * Describes the enum vss.ErrorCode.
 */
export const ErrorCodeSchema: GenEnum<ErrorCode> = /*@__PURE__*/ enumDesc(file_vss, 0)
